[build-system]
requires = ["scikit-build-core>=0.5.0", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "pyscan"
version = "0.1.0"
description = "Python bindings for spatial scan statistics"
authors = [{ name = "Simon Gonzalez", email = "simon.pedro.g@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = ["Programming Language :: Python :: 3"]

[tool.scikit-build]
wheel.packages = ["pyscan"]
cmake.minimum-version = "3.15"
cmake.verbose = true
